### ISSUE TITLE
Implement remembering users across sessions

### ISSUE THREAD

**Issue by ashpil** [cucapra/gator-study#12]
We're going to need some way to let users complete the tutorial across multiple sessions. 

I think the smoothest way would be to just use some form of cookies or [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API), as then we don't have to know the user's IP.

The question is whether we want users to be able to override this ability somehow - like can we let them restart their session at will (does this introduce any bias)? Do we also give users some sort of token to let them continue their session if cookies are deleted (I vote no, seems to be too complicated for too little gain)?

**Comment by sampsyo** [comment]
A way we have discussed to do this in the past has been, yes, to provide a unique token. This would (a) be totally transparent, as we wouldn't need to store any cookies or whatever, (b) make it easy to "reset" (just throw away your token!), and (c) enable resume under extenuating circumstances (such as moving to another browser).

**Comment by ashpil** [comment]
> 
> 
> A way we have discussed to do this in the past has been, yes, to provide a unique token. This would (a) be totally transparent, as we wouldn't need to store any cookies or whatever, (b) make it easy to "reset" (just throw away your token!), and (c) enable resume under extenuating circumstances (such as moving to another browser).

Yeah, after thinking about that more I'm leaning towards that more than cookies, as cookies seem to basically be all the work of that, and more.
