### ISSUE TITLE
File Loading Bug with Flask

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/gator-study#7]
After running `make run` and navigating to the created server, click "returning user", then "submit" to start the main render page.  At this point, the renderer should fail to load due to a console error: "Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined".  This error was reproduced on two separate machines, and seems to be related to [this line of code](https://github.com/cucapra/gator-study/blob/python-parcel-bundle/js/visualizer.js#L5) in the visualizer.  This error apparently only happens after loading in Flask, although I do recall an earlier issue in this project with the line `import fs from 'fs';`, which may or may not be related.

Note that this bug appears on the [python-bundle-parcel](https://github.com/cucapra/gator-study/tree/python-parcel-bundle) branch of the current build.

**Comment by sampsyo** [comment]
To track down the root cause, can you verify the the problem does _not_ occur when serving plain files? Like, with `python3 -m http.server`. And if not, the next thing to do is to triple-check that the JavaScript being served (e.g., to `curl`) is byte-for-byte identical between the two settings (Flask and non-Flask).

If it is identical, we have a mysterious problem but at least Flask is behaving as expected. If it's not, then the thing to do is to figure out why the files are different.

**Comment by Checkmate50** [comment]
Finally had a chance to look at this.  When running `python -m http.server`, I run into the issue that we have import statements that simply don't work without Flask (from what I understand).  Specifically, it throws a fit with the line: `import { Renderer } from './visualizer.js';`, which it says `Uncaught Syntax Error: Cannot use import statement outside a module`

**Comment by sampsyo** [comment]
You will need to compile with Parcel first. That's what resolves the imports.

**Comment by sampsyo** [comment]
This is the fix I posted on Slack.

```diff
diff --git a/templates/layouts/gpt.html b/templates/layouts/gpt.html
index 9e89029..f2a35f6 100644
--- a/templates/layouts/gpt.html
+++ b/templates/layouts/gpt.html
@@ -15,7 +15,7 @@
         <link type = "text/css" rel="stylesheet" href= "{{ url_for('static', filename='css/styles.css') }}"/>
 
         <!-- <script src="/l/gatorc.bc.js"></script> -->
-        <script src="{{ url_for('static', filename='js/main_page.js') }}" type="module"></script>
+        <script src="{{ url_for('static', filename='js/main_page.js') }}"></script>
 
     </head>
```
