### ISSUE TITLE
Code cleanup for Flask-based setup

### ISSUE THREAD

**Issue by sampsyo** [cucapra/gator-study#8]
I know it's in progress, but I noted a few miscellaneous cleanup things that need to be done to the Flask-based server version:

- Remove unused imports from the top of `app.py`.
- *Definitely* remove `flask_assets` and `webassets`, which we don't need because they are redundant with Parcel and could cause confusion it runs after Parcel.
- Remove unused dependencies from `package.json`.
- Update the README to describe how to use the Flask server.
- Remove the need to manually copy stuff from `dist` to `templates/static`. Just serve stuff right out of `dist`.
- Manually modifying `app._static_folder` seems like a bad idea because it is using an undocumented feature. Try a simpler way to serve the static files.
- Merge the branch with master.

**Comment by ashpil** [comment]
I think this can be closed now that the Svelte PR is in.
